name: CI
on: [push, pull_request]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: 3.13
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements_dev.txt
    - name: Run tests
      run: pytest
